#!/usr/bin/env python3
"""Pull one purchased part's solid out of the released arm assembly.

`third_party/partcad.yaml` lists where a better shape for a bought part would
come from, in order, and the third entry is this: the released full-arm STEP
file, which carries the geometry the designers actually worked against. For a
handful of parts it is the *only* source - nobody publishes a CAD model of a
KA3x12 self-tapping screw or of a 4 mm dowel pin, and the module 1 gear the
gripper is driven by is a part this repository has no generator for yet.

Those parts had no shape at all, so they were absent from every assembly and
every bill of materials: 80 of the DM arm's 326 components and 49 of the RS
arm's. The solids are already in this repository, inside the released assembly;
this writes each one out on its own, in its own coordinates, so that a part can
be declared from it.

What comes out is the vendor's own geometry as the designers received it, not an
envelope, so it is the right thing to check a clearance against. It is also not
something this repository measured, and the declarations say so.

Run it from the repository root:

    python3 tools/extract_vendor_parts.py

It rewrites the files under third_party/vendor/ and is idempotent.
"""

import os
import sys

from OCP.IFSelect import IFSelect_RetDone
from OCP.Interface import Interface_Static
from OCP.STEPCAFControl import STEPCAFControl_Reader
from OCP.STEPControl import STEPControl_AsIs
from OCP.STEPControl import STEPControl_Writer
from OCP.TCollection import TCollection_ExtendedString
from OCP.TDataStd import TDataStd_Name
from OCP.TDF import TDF_Label, TDF_LabelSequence
from OCP.TDocStd import TDocStd_Document
from OCP.XCAFDoc import XCAFDoc_DocumentTool, XCAFDoc_ShapeTool

# Which release to take each part from, what it is called in it, and what to
# write it as. The DM release is the source for all of them: both releases hold
# the same screws and the same gear, and taking each from one place means one
# file rather than two that can disagree.
OUTPUT = "third_party/vendor"

# Which release each part comes out of, and what to write it as.
#
# Most of these are in both releases, and where they are, the two models are the
# same solid in the same frame - byte for byte the same box and the same volume -
# so one file serves both arms and the sharing is a fact rather than a hope. The
# exceptions are the parts only one arm uses (each arm's actuators, the RS arm's
# connectors) and the one part both arms call by the same name and model
# differently: the RS release's 6803 is 28 mm across with a flange where the DM
# release's is a plain 26 mm bearing.
DM = "hardware/reBot_B601_DM/reBot_B601_DM_v1.1_20260425.step"
RS = "hardware/reBot_B601_RS/reBot_B601_RS_v1.0_20260625.step"

WANTED = {
    DM: {
        # Nobody publishes a model of these at all.
        "GEAR-1M16C": "gear-m1-16t-b6",
        "KA3-12": "screw-ka3x12",
        "PIN-D3L8": "pin-d3x8",
        "PIN-D4L7": "pin-d4x7",
        "PIN-D4L10": "pin-d4x10",
        "PIN-D4L14": "pin-d4x14",
        "S-M4-5-JIMI": "screw-m4x5-set",
        # These had an envelope drawn from a datasheet. An envelope is the right
        # shape to check a clearance against and the wrong frame to place a part
        # in: a transformation read off the release only means what it says with
        # the model it was read from, so an envelope put there by it lands
        # origin-on-origin rather than face-on-face. The MGN9 rail was the
        # clearest case - 170 mm long, laid along X where the release has it
        # along Z, 170 mm out of place.
        # Not the actuators. Their vendor models are 17 to 25 MB each, 74 MB for the
        # four, which is not a thing to add to a git repository for a shape that is
        # a cylinder to everything downstream. They stay envelopes - and the
        # measurements above give those envelopes the vendor's own frame, which is
        # the half of it that a placement needs.
        "6707ZZ": "bearing-6707zz",
        "6803ZZ": "bearing-6803zz",
        "AXK5578": "bearing-axk5578",
        "RAIL-170": "rail-mgn9-170",
        "SLIDER": "carriage-mgn9c",
        "SILICONE-L30W9H2": "pad-silicone-30x9x2",
        # The fasteners, for the same reason and with the same effect: 160 of the
        # DM arm's 326 components are screws, and an ISO screw generated by
        # //pub/std/metric/cqwarehouse - which is what they were - is a different
        # model in a different frame from the one the release placed. Every one of
        # these is drawn head at the origin running along its own +Y, which is why
        # one file serves both arms wherever both use the screw.
        "HM3-6": "screw-hm3x6",
        "HM3-12": "screw-hm3x12",
        "HM3-26": "screw-hm3x25",
        "HM4-75": "screw-hm4x75",
        "KM3-7": "screw-km3x7",
        "KM3-8-XIAO": "screw-km3x8-micro",
        "KM3-9": "screw-km3x9",
        "KM3-12": "screw-km3x12",
        "KM3-16": "screw-km3x16",
    },
    RS: {
        "9-XT30_2_2-V1": "connector-xt30-2x2",
        "9-SOCKET-XT30-2-2": "connector-xt30-2x2-socket",
        "6-BEARING-F6803ZZ-OD26ID17H5": "bearing-f6803zz",
        "7-HM3-8": "screw-hm3x8",
        "7-HM3-30": "screw-hm3x30",
        "7-HM4-8": "screw-hm4x8",
        "7-HM4-16": "screw-hm4x16",
        "7-HM4-70": "screw-hm4x70",
    },
}


def extract(source, wanted):
    doc = TDocStd_Document(TCollection_ExtendedString("doc"))
    reader = STEPCAFControl_Reader()
    reader.SetNameMode(True)
    if not reader.ReadFile(source):
        sys.exit("cannot read %s" % source)
    reader.Transfer(doc)
    shape_tool = XCAFDoc_DocumentTool.ShapeTool_s(doc.Main())

    def name_of(label):
        attr = TDataStd_Name()
        if label.FindAttribute(TDataStd_Name.GetID_s(), attr):
            return attr.Get().ToExtString()
        return ""

    # Every product of the document, by name: a product is the part itself, in its
    # own coordinates, as against a component, which is that part put somewhere.
    products = {}
    labels = TDF_LabelSequence()
    shape_tool.GetShapes(labels)
    for i in range(1, labels.Length() + 1):
        label = labels.Value(i)
        if XCAFDoc_ShapeTool.IsAssembly_s(label) or XCAFDoc_ShapeTool.IsReference_s(label):
            continue
        products.setdefault(name_of(label).split(":")[0], label)

    os.makedirs(OUTPUT, exist_ok=True)
    missing = []
    for product, basename in sorted(wanted.items()):
        label = products.get(product)
        if label is None:
            missing.append(product)
            continue
        shape = XCAFDoc_ShapeTool.GetShape_s(label)
        path = os.path.join(OUTPUT, basename + ".step")
        writer = STEPControl_Writer()
        # Millimetres and AP214, which is what the releases themselves are in.
        Interface_Static.SetCVal_s("write.step.unit", "MM")
        Interface_Static.SetCVal_s("write.step.schema", "AP214IS")
        Interface_Static.SetCVal_s("write.step.product.name", basename)
        writer.Transfer(shape, STEPControl_AsIs)
        # IFSelect_RetDone is the success value; anything else is a failure.
        if writer.Write(path) != IFSelect_RetDone:
            sys.exit("cannot write %s" % path)
        print("%-24s -> %s" % (product, path))
    if missing:
        sys.exit("not in %s: %s" % (source, ", ".join(missing)))


if __name__ == "__main__":
    for source, wanted in WANTED.items():
        extract(source, wanted)
